# Generated by scripts/teitunnel.mjs from the release's SHA256SUMS.txt. Don't edit by hand.
cask "teitunnel" do
  version "0.3.0"
  sha256 "c4535a1683cd697c522058874403a81ea65cba19de7e6e6bd5b26d9860959509"

  url "https://github.com/teispace/teitunnel/releases/download/v#{version}/Teitunnel_#{version}_universal.dmg"
  name "Teitunnel"
  desc "Cloudflare Tunnel app: share localhost and publish apps on your domain"
  homepage "https://teitunnel.teispace.com/"

  livecheck do
    url :url
    strategy :github_latest
  end

  auto_updates true
  depends_on macos: :sonoma

  app "Teitunnel.app"
  binary "#{appdir}/Teitunnel.app/Contents/MacOS/teitunnel-cli", target: "teitunnel"

  zap trash: [
    "~/Library/Application Support/com.teispace.teitunnel",
    "~/Library/Caches/com.teispace.teitunnel",
    "~/Library/HTTPStorages/com.teispace.teitunnel",
    "~/Library/LaunchAgents/com.teispace.teitunnel.connector.*.plist",
    "~/Library/Logs/com.teispace.teitunnel",
    "~/Library/Preferences/com.teispace.teitunnel.plist",
    "~/Library/Saved Application State/com.teispace.teitunnel.savedState",
    "~/Library/WebKit/com.teispace.teitunnel",
  ]
end
