# Generated by scripts/teitunnel.mjs from the release's SHA256SUMS.txt. Don't edit by hand.
class TeitunnelCli < Formula
  desc "Manage Cloudflare Tunnel routes from the terminal, servers and containers"
  homepage "https://teitunnel.teispace.com/"
  license "MIT"

  if OS.mac?
    url "https://github.com/teispace/teitunnel/releases/download/v0.5.0/teitunnel-cli_0.5.0_macos-universal.zip"
    sha256 "6dc424562de7d314aff6d70b7eb134705036ab384a326e417f86d3ee284ab9e6"
  elsif Hardware::CPU.arm?
    url "https://github.com/teispace/teitunnel/releases/download/v0.5.0/teitunnel-cli_0.5.0_linux-arm64.tar.gz"
    sha256 "bf5e9823ce0493c7ab1ddd56a365c7573c3098f933670652c219edc886b6fde2"
  else
    url "https://github.com/teispace/teitunnel/releases/download/v0.5.0/teitunnel-cli_0.5.0_linux-x64.tar.gz"
    sha256 "9256de131b39c5313e9c20ed8f4cb43e07b6b87ac93aa3de7df3f485b1db4c02"
  end

  livecheck do
    url :stable
    strategy :github_latest
  end

  depends_on "cloudflared"

  def install
    bin.install "teitunnel"
    generate_completions_from_executable(bin/"teitunnel", "completions")
  end

  test do
    assert_match "teitunnel #{version}", shell_output("#{bin}/teitunnel --version")
  end
end
