# Generated by scripts/teitunnel.mjs from the release's SHA256SUMS.txt. Don't edit by hand.
class TeitunnelCli < Formula
  desc "Manage Cloudflare Tunnel routes from the terminal, servers and containers"
  homepage "https://teitunnel.teispace.com/"
  license "MIT"

  if OS.mac?
    url "https://github.com/teispace/teitunnel/releases/download/v0.4.0/teitunnel-cli_0.4.0_macos-universal.zip"
    sha256 "720cd5557a71db3cdb5e9de38eba3198c17d3ec1191da8fe4efec2eb66f42f54"
  elsif Hardware::CPU.arm?
    url "https://github.com/teispace/teitunnel/releases/download/v0.4.0/teitunnel-cli_0.4.0_linux-arm64.tar.gz"
    sha256 "8ccc8cd86c68aa3b74a1dadd8baa9c2db2e832bfd9fd6a4f6cfa94e7a1814ffc"
  else
    url "https://github.com/teispace/teitunnel/releases/download/v0.4.0/teitunnel-cli_0.4.0_linux-x64.tar.gz"
    sha256 "c28639dbd2c6732ac647252dba7cb831dc9914d292c76c7102b392d0c194bc50"
  end

  livecheck do
    url :stable
    strategy :github_latest
  end

  depends_on "cloudflared"

  def install
    bin.install "teitunnel"
    generate_completions_from_executable(bin/"teitunnel", "completions")
  end

  test do
    assert_match "teitunnel #{version}", shell_output("#{bin}/teitunnel --version")
  end
end
