# Generated by scripts/teitunnel.mjs from the release's SHA256SUMS.txt. Don't edit by hand.
class TeitunnelCli < Formula
  desc "Manage Cloudflare Tunnel routes from the terminal, servers and containers"
  homepage "https://teitunnel.teispace.com/"
  license "MIT"

  if OS.mac?
    url "https://github.com/teispace/teitunnel/releases/download/v0.3.1/teitunnel-cli_0.3.1_macos-universal.zip"
    sha256 "6ae08a75d09cce741e0fa89c99592d762913df19282f7e72d9777384e55ce735"
  elsif Hardware::CPU.arm?
    url "https://github.com/teispace/teitunnel/releases/download/v0.3.1/teitunnel-cli_0.3.1_linux-arm64.tar.gz"
    sha256 "9c0d65b4a23db6a183f38c9697530875c377e72bd1e8d825500b34538343958e"
  else
    url "https://github.com/teispace/teitunnel/releases/download/v0.3.1/teitunnel-cli_0.3.1_linux-x64.tar.gz"
    sha256 "9c405af3b3bb6a13bd1a0d3aaffecf6e6b51eb783e3dbfec6b022ee40029262f"
  end

  livecheck do
    url :stable
    strategy :github_latest
  end

  depends_on "cloudflared"

  def install
    bin.install "teitunnel"
    generate_completions_from_executable(bin/"teitunnel", "completions")
  end

  test do
    assert_match "teitunnel #{version}", shell_output("#{bin}/teitunnel --version")
  end
end
