// Renders Casks/teitunnel.rb and Formula/teitunnel-cli.rb for a Teitunnel release from
// its SHA256SUMS.txt, so every checksum comes from the release itself (the workflow
// verifies that file's build provenance first).
//
//   node scripts/teitunnel.mjs <version> <SHA256SUMS.txt>

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const repo = "https://github.com/teispace/teitunnel";

/** The files the tap installs, by role. */
export const files = (v) => ({
  dmg: `Teitunnel_${v}_universal.dmg`,
  cliMac: `teitunnel-cli_${v}_macos-universal.zip`,
  cliLinuxX64: `teitunnel-cli_${v}_linux-x64.tar.gz`,
  cliLinuxArm64: `teitunnel-cli_${v}_linux-arm64.tar.gz`,
});

/** `sha256  name` lines to a map, refusing anything malformed. */
export function parseSums(text) {
  const sums = new Map();
  for (const line of text.split("\n")) {
    if (!line.trim()) continue;
    const m = /^([0-9a-f]{64}) [ *]?(\S+)$/.exec(line.trim());
    if (!m) throw new Error(`Unexpected line in SHA256SUMS: ${line}`);
    sums.set(m[2], m[1]);
  }
  return sums;
}

export function render(version, sums) {
  if (!/^\d+\.\d+\.\d+(-[0-9A-Za-z.]+)?$/.test(version)) {
    throw new Error(`Not a version: ${version}`);
  }
  const f = files(version);
  const sha = (name) => {
    const s = sums.get(name);
    if (!s) throw new Error(`${name} is missing from SHA256SUMS`);
    return s;
  };
  const cask = `# Generated by scripts/teitunnel.mjs from the release's SHA256SUMS.txt. Don't edit by hand.
cask "teitunnel" do
  version "${version}"
  sha256 "${sha(f.dmg)}"

  url "${repo}/releases/download/v#{version}/Teitunnel_#{version}_universal.dmg"
  name "Teitunnel"
  desc "Cloudflare Tunnel app: share localhost and publish apps on your domain"
  homepage "https://teitunnel.teispace.com/"

  livecheck do
    url :url
    strategy :github_latest
  end

  auto_updates true
  depends_on macos: :sonoma

  app "Teitunnel.app"
  binary "#{appdir}/Teitunnel.app/Contents/MacOS/teitunnel-cli", target: "teitunnel"

  zap trash: [
    "~/Library/Application Support/com.teispace.teitunnel",
    "~/Library/Caches/com.teispace.teitunnel",
    "~/Library/HTTPStorages/com.teispace.teitunnel",
    "~/Library/LaunchAgents/com.teispace.teitunnel.connector.*.plist",
    "~/Library/Logs/com.teispace.teitunnel",
    "~/Library/Preferences/com.teispace.teitunnel.plist",
    "~/Library/Saved Application State/com.teispace.teitunnel.savedState",
    "~/Library/WebKit/com.teispace.teitunnel",
  ]
end
`;
  const dl = `${repo}/releases/download/v${version}`;
  const formula = `# Generated by scripts/teitunnel.mjs from the release's SHA256SUMS.txt. Don't edit by hand.
class TeitunnelCli < Formula
  desc "Manage Cloudflare Tunnel routes from the terminal, servers and containers"
  homepage "https://teitunnel.teispace.com/"
  license "MIT"

  if OS.mac?
    url "${dl}/${f.cliMac}"
    sha256 "${sha(f.cliMac)}"
  elsif Hardware::CPU.arm?
    url "${dl}/${f.cliLinuxArm64}"
    sha256 "${sha(f.cliLinuxArm64)}"
  else
    url "${dl}/${f.cliLinuxX64}"
    sha256 "${sha(f.cliLinuxX64)}"
  end

  livecheck do
    url :stable
    strategy :github_latest
  end

  depends_on "cloudflared"

  def install
    bin.install "teitunnel"
    generate_completions_from_executable(bin/"teitunnel", "completions")
  end

  test do
    assert_match "teitunnel #{version}", shell_output("#{bin}/teitunnel --version")
  end
end
`;
  return { cask, formula };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const [version, sumsPath] = process.argv.slice(2);
  if (!version || !sumsPath) {
    process.stderr.write("usage: node scripts/teitunnel.mjs <version> <SHA256SUMS.txt>\n");
    process.exit(2);
  }
  const { cask, formula } = render(version, parseSums(readFileSync(sumsPath, "utf8")));
  writeFileSync("Casks/teitunnel.rb", cask);
  writeFileSync("Formula/teitunnel-cli.rb", formula);
  process.stdout.write(`Rendered Teitunnel ${version}\n`);
}
